### ISSUE TITLE
Pressing tab lose focus

### ISSUE THREAD

**Issue by SamyPesse** [SamyPesse/slate-edit-code#4]
Focus of editing is lost when pressing tab even if we force Slate to focus after the transformation: https://github.com/SamyPesse/slate-edit-code/blob/master/lib/onTab.js#L20

It may be related to the event being propagated to the `document` or `window`. Maybe calling `event.stopPropagation()` will solve the issue.

**Comment by SamyPesse** [comment]
Adding `event.stopPropagation()` doesn't solve it.

@ianstormtaylor any idea?

**Comment by ianstormtaylor** [comment]
Hmm that's weird. Here's a fiddle with a simple tab handler that seems to work: https://jsfiddle.net/88pm8ztd/

---

Also since I peeked at the code, I noticed: `insertText` will `delete` first for you if the selection is expanded, so no need to check there!

**Comment by SamyPesse** [comment]
Yes after investigation, the bug is specific to the application.

**Comment by SamyPesse** [comment]
@ianstormtaylor It's broken with latest Slate (0.10.8).

This time, it's broken in the example also: https://samypesse.github.io/slate-prism/

**Comment by ianstormtaylor** [comment]
Are you sure it's not something elsewhere that's causing it? It seems like the JSFiddle still works for the most basic usage, and it looks like it's using the latest Slate in it. But I can't quite tell.

**Comment by SamyPesse** [comment]
Sorry it was a very stupid error (`e` instead of `event`)

**Comment by ianstormtaylor** [comment]
Haha no worries, I do that often! 😁
